//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 12:24:47  on 16 Март 2003 г.
//
//	Generated for file: C:\Work\Palm\Kozel\Project\Rsc\OS5\cards.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: Talt 5001
#define ScreenAlert                               5001
#define Screen                                    0

//	Resource: Talt 5000
#define COLOR_Alert                               5000
#define COLOR_DEPTH_8                             0


//	Resource: PICT 1500
#define BitmapID1500Bitmap                        1500

//	Resource: PICT 1501
#define BitmapID1501Bitmap                        1501

//	Resource: PICT 1502
#define BitmapID1502Bitmap                        1502

//	Resource: PICT 1503
#define BitmapID1503Bitmap                        1503

//	Resource: PICT 1504
#define BitmapID1504Bitmap                        1504

//	Resource: PICT 1505
#define BitmapID1505Bitmap                        1505

//	Resource: PICT 2006
#define BitmapID2006Bitmap                        2006

//	Resource: PICT 2007
#define BitmapID2007Bitmap                        2007

//	Resource: PICT 1600
#define BitmapID1600Bitmap                        1600

//	Resource: PICT 1601
#define BitmapID1601Bitmap                        1601

//	Resource: PICT 1602
#define BitmapID1602Bitmap                        1602

//	Resource: PICT 1603
#define BitmapID1603Bitmap                        1603

//	Resource: PICT 1604
#define BitmapID1604Bitmap                        1604

//	Resource: PICT 1605
#define BitmapID1605Bitmap                        1605

//	Resource: PICT 2008
#define BitmapID2008Bitmap                        2008

//	Resource: PICT 2009
#define BitmapID2009Bitmap                        2009

//	Resource: PICT 1700
#define BitmapID170Bitmap                         1700

//	Resource: PICT 1701
#define BitmapID1701Bitmap                        1701

//	Resource: PICT 1702
#define BitmapID1702Bitmap                        1702

//	Resource: PICT 1703
#define BitmapID1703Bitmap                        1703

//	Resource: PICT 1704
#define BitmapID1704Bitmap                        1704

//	Resource: PICT 1705
#define BitmapID1705Bitmap                        1705

//	Resource: PICT 2010
#define BitmapID2010Bitmap                        2010

//	Resource: PICT 2011
#define BitmapID2011Bitmap                        2011

//	Resource: PICT 2012
#define BitmapID2012Bitmap                        2012

//	Resource: PICT 1801
#define BitmapID1801Bitmap                        1801

//	Resource: PICT 1802
#define BitmapID1802Bitmap                        1802

//	Resource: PICT 1803
#define BitmapID1803Bitmap                        1803

//	Resource: PICT 1804
#define BitmapID1804Bitmap                        1804

//	Resource: PICT 1805
#define BitmapID1805Bitmap                        1805

//	Resource: PICT 2013
#define BitmapID2013Bitmap                        2013

//	Resource: PICT 2014
#define BitmapID2014Bitmap                        2014

//	Resource: PICT 1400
#define BitmapID1400Bitmap                        1400

//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000

//	Resource: PICT 1100
#define BitmapID1100Bitmap                        1100

//	Resource: PICT 1200
#define BitmapID1200Bitmap                        1200

//	Resource: PICT 1300
#define BitmapID1300Bitmap                        1300

//	Resource: PICT 3000
#define BitmapID3000Bitmap                        3000


//	Resource: tbmf 1400
#define SuitBitmapFamily                          1400

//	Resource: tbmf 2006
#define BJBitmapFamily                            2006

//	Resource: tbmf 1801
#define K8BitmapFamily                            1801

//	Resource: tbmf 1802
#define K9BitmapFamily                            1802

//	Resource: tbmf 1803
#define KKBitmapFamily                            1803

//	Resource: tbmf 1804
#define K10BitmapFamily                           1804

//	Resource: tbmf 1805
#define KABitmapFamily                            1805

//	Resource: tbmf 2007
#define CJBitmapFamily                            2007

//	Resource: tbmf 2008
#define PJBitmapFamily                            2008

//	Resource: tbmf 1700
#define P6BitmapFamily                            1700

//	Resource: tbmf 1701
#define P8BitmapFamily                            1701

//	Resource: tbmf 1702
#define P9BitmapFamily                            1702

//	Resource: tbmf 1703
#define PKBitmapFamily                            1703

//	Resource: tbmf 1704
#define P10BitmapFamily                           1704

//	Resource: tbmf 1705
#define PABitmapFamily                            1705

//	Resource: tbmf 2009
#define KJBitmapFamily                            2009

//	Resource: tbmf 2010
#define BQBitmapFamily                            2010

//	Resource: tbmf 1600
#define C6BitmapFamily                            1600

//	Resource: tbmf 1601
#define C8BitmapFamily                            1601

//	Resource: tbmf 1602
#define C9BitmapFamily                            1602

//	Resource: tbmf 1603
#define CKBitmapFamily                            1603

//	Resource: tbmf 1604
#define C10BitmapFamily                           1604

//	Resource: tbmf 1605
#define CABitmapFamily                            1605

//	Resource: tbmf 2011
#define CQBitmapFamily                            2011

//	Resource: tbmf 2012
#define PQBitmapFamily                            2012

//	Resource: tbmf 1502
#define B9BitmapFamily                            1502

//	Resource: tbmf 1501
#define B8BitmapFamily                            1501

//	Resource: tbmf 1503
#define BKBitmapFamily                            1503

//	Resource: tbmf 1504
#define B10BitmapFamily                           1504

//	Resource: tbmf 1505
#define BABitmapFamily                            1505

//	Resource: tbmf 2013
#define KQBitmapFamily                            2013

//	Resource: tbmf 2014
#define K6BitmapFamily                            2014

//	Resource: tbmf 1500
#define B6BitmapFamily                            1500

//	Resource: tbmf 1300
#define GetTopBitmapFamily                        1300

//	Resource: tbmf 1200
#define GetRightBitmapFamily                      1200

//	Resource: tbmf 1100
#define GetLeftBitmapFamily                       1100

//	Resource: tbmf 1000
#define GetBottomBitmapFamily                     1000

//	Resource: tbmf 3000
#define ProgressBitmapFamily                      3000

