//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 13:44:36  on 27 Ìàğò 2003 ã.
//
//	Generated for file: C:\Work\Palm\Kozel\Project\Rsc\Kozel.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Êîçåë"
//
//	Palm App Version:		"1.02"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 62, Top Origin = 125, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1101BitMap                    2000	//(Left Origin = 51, Top Origin = 73, Bitmap Resource ID = 2000, Usable = 1)
#define AboutTitleLabel                           1102	//(Left Origin = 68, Top Origin = 49, Usable = 1, Font = Bold 12)
#define AboutText1Label                           1103	//(Left Origin = 46, Top Origin = 18, Usable = 1, Font = Standard)
#define AboutVersionLabel                         1104	//(Left Origin = 105, Top Origin = 142, Usable = 1, Font = Standard)
#define AboutUnnamed1106Label                     1106	//(Left Origin = 3, Top Origin = 142, Usable = 1, Font = Standard)

//	Resource: tFRM 1200
#define ConfigForm                                1200	//(Left Origin = 1, Top Origin = 1, Width = 158, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1202)
#define ConfigDoneButton                          1202	//(Left Origin = 19, Top Origin = 141, Width = 60, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ConfigCancelButton                        1203	//(Left Origin = 87, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ConfigShowLabelsCheckbox                  1201	//(Left Origin = 3, Top Origin = 107, Width = 140, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ConfigAutoStepCheckbox                    1213	//(Left Origin = 3, Top Origin = 123, Width = 155, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ConfigPalm1Checkbox                       1216	//(Left Origin = 108, Top Origin = 46, Width = 50, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define ConfigPalm2Checkbox                       1217	//(Left Origin = 108, Top Origin = 59, Width = 50, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define ConfigPalm3Checkbox                       1218	//(Left Origin = 108, Top Origin = 73, Width = 50, Height = 12, Usable = 0, Selected = 1, Group ID = 0, Font = Standard)
#define ConfigName0Field                          1209	//(Left Origin = 7, Top Origin = 32, Width = 100, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 20, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConfigName1Field                          1210	//(Left Origin = 7, Top Origin = 46, Width = 100, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 20, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConfigName2Field                          1211	//(Left Origin = 7, Top Origin = 60, Width = 100, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 20, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConfigName3Field                          1212	//(Left Origin = 7, Top Origin = 74, Width = 100, Height = 12, Usable = 0, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 20, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConfigUnnamed1207GraffitiShift            1207	//(Left Origin = 148, Top Origin = 147)
#define ConfigUnnamed1204Label                    1204	//(Left Origin = 12, Top Origin = 18, Usable = 1, Font = Standard)
#define ConfigUnnamed1214Label                    1214	//(Left Origin = 23, Top Origin = 89, Usable = 1, Font = Standard)
#define ConfigPlayers3PushButton                  1205	//(Left Origin = 67, Top Origin = 17, Width = 30, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define ConfigPlayers4PushButton                  1206	//(Left Origin = 100, Top Origin = 17, Width = 50, Height = 12, Usable = 0, Group ID = 1, Font = Standard)
#define ConfigAiBadPushButton                     1220	//(Left Origin = 111, Top Origin = 89, Width = 10, Height = 10, Usable = 1, Group ID = 2, Font = Standard)
#define ConfigAiPoorPushButton                    1221	//(Left Origin = 124, Top Origin = 89, Width = 10, Height = 10, Usable = 1, Group ID = 2, Font = Standard)
#define ConfigAiNormalPushButton                  1222	//(Left Origin = 137, Top Origin = 89, Width = 10, Height = 10, Usable = 1, Group ID = 2, Font = Standard)
#define ConfigGroupID                             1
#define ConfigGroupID2                            2

//	Resource: tFRM 1300
#define GoRoundForm                               1300	//(Left Origin = 30, Top Origin = 30, Width = 100, Height = 70, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define GoRoundGoButton                           1305	//(Left Origin = 12, Top Origin = 47, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GoRoundCancelButton                       1306	//(Left Origin = 54, Top Origin = 47, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GoRoundBPushButton                        1301	//(Left Origin = 68, Top Origin = 22, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define GoRoundCPushButton                        1302	//(Left Origin = 53, Top Origin = 22, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define GoRoundPPushButton                        1303	//(Left Origin = 38, Top Origin = 22, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define GoRoundKPushButton                        1304	//(Left Origin = 23, Top Origin = 22, Width = 12, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define GoRoundGroupID                            1

//	Resource: tFRM 1400
#define StatisticsForm                            1400	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1000, Menu Bar ID = 0, Default Button ID = 0)
#define StatisticsOkButton                        1401	//(Left Origin = 8, Top Origin = 127, Width = 70, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define StatisticsResetButton                     1403	//(Left Origin = 91, Top Origin = 127, Width = 60, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 0, Font = Bold 12)
#define StatisticsUnnamed1402Label                1402	//(Left Origin = 11, Top Origin = 27, Usable = 1, Font = LED)
#define StatisticsUnnamed1404Label                1404	//(Left Origin = 11, Top Origin = 50, Usable = 1, Font = LED)
#define StatisticsUnnamed1407Label                1407	//(Left Origin = 11, Top Origin = 96, Usable = 0, Font = LED)
#define StatisticsUnnamed1409Label                1409	//(Left Origin = 11, Top Origin = 73, Usable = 1, Font = LED)
#define StatisticsFirstScoreLabel                 1414	//(Left Origin = 122, Top Origin = 29, Usable = 1, Font = Bold 12)
#define StatisticsUnnamed1415Label                1415	//(Left Origin = 122, Top Origin = 52, Usable = 1, Font = Bold 12)
#define StatisticsUnnamed1416Label                1416	//(Left Origin = 122, Top Origin = 75, Usable = 1, Font = Bold 12)
#define StatisticsUnnamed1417Label                1417	//(Left Origin = 122, Top Origin = 98, Usable = 0, Font = Bold 12)
#define StatisticsFirstNameLabel                  1420	//(Left Origin = 28, Top Origin = 30, Usable = 1, Font = Bold 12)
#define StatisticsUnnamed1421Label                1421	//(Left Origin = 28, Top Origin = 52, Usable = 1, Font = Bold 12)
#define StatisticsUnnamed1422Label                1422	//(Left Origin = 28, Top Origin = 75, Usable = 1, Font = Bold 12)
#define StatisticsUnnamed1423Label                1423	//(Left Origin = 28, Top Origin = 98, Usable = 0, Font = Bold 12)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define HelloAlert                                1100
#define HelloOK                                   0

//	Resource: Talt 1200
#define PrikupAlert                               1200
#define PrikupOK                                  0

//	Resource: Talt 1000
#define NextPlayerAlert                           1000
#define NextPlayer                                0

//	Resource: Talt 1300
#define ShowAlert                                 1300
#define ShowOK                                    0

//	Resource: Talt 1400
#define BadStepAlert                              1400
#define BadStep                                   0

//	Resource: Talt 1500
#define TrumpMoveAlert                            1500
#define TrumpMove                                 0

//	Resource: Talt 1600
#define LosserAlert                               1600
#define Losser                                    0

//	Resource: Talt 1700
#define DrawAlert                                 1700
#define Draw                                      0

//	Resource: Talt 1800
#define OneLossAlert                              1800
#define OneLoss                                   0

//	Resource: Talt 1900
#define TwoLossAlert                              1900
#define TwoLoss                                   0

//	Resource: Talt 2000
#define CatchAlert                                2000
#define Catch                                     0


//	Resource: MBAR 1000
#define KozelMainMenuBar                          1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsMenuItem1000                       1000	// Menu Text: Íà÷àòü íîâóş            
#define OptionsMenuItem1001                       1001	// Menu Text: Íàñòğîéêà
#define OptionsMenuItem1002                       1002	// Menu Text: Ñòàòèñòèêà

//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpMenuItem1100                          1100	// Menu Text: Ïğàâèëà   
#define HelpMenuItem1101                          1101	// Menu Text: ×òî ÿ âèæó?       
#define HelpMenuItem1102                          1102	// Menu Text: Î ïğîãğàììå   


//	Resource: tSTR 1900
#define ThatIseeString                            1900	// "åˆ¿ ˆ¶˜ ‰’—  ”˜–”¶˜¶”‰ˆ’ •” “ˆ–˜Ø“:  ‡—‡’, ÖŒ¶‰, •, ¶Œ–˜, ”¶Ø.  €‘Ø ˜”‹”, Ö˜”‡"

//	Resource: tSTR 1800
#define PrikupString                              1800	// "ë‡Ö’” –Š‰ˆŒ˜–Ø “ˆ–˜Ÿ (’ˆ•¶“Œ¶, ŒŠ’–˜‰Œ’’ˆØ ‡—‡’ˆ), ‘ ”Ö (ŠŒ–Ø˜, ”¶”‘)."

//	Resource: tSTR 1700
#define BadMoveString                             1700	// "î ‰ˆ– ¾Œ Œ–˜Ÿ ı˜ˆ “ˆ–˜Ÿ - ’Œ›”¶”¿”. ñˆ  ùŒ˜¶Œ› •”‘—Ö˜Ÿ “”¾’”."

//	Resource: tSTR 1600
#define TrumpMoveString                           1600	// "î ‰ˆ– Œ–˜Ÿ ’Œ”¶’Œ ˆ¶˜, ‡ˆ‰Ÿ˜Œ–Ÿ –’ˆÖˆ‘ˆ ”˜ ’›.  é‹¶ˆ ‰ ¾‰—ş - ‰ˆ“ ˆ•–ˆ‘ ‡ ùŒ˜¶Œ›.  "

//	Resource: tSTR 1400
#define DrawString                                1400	// "å–Œ‹” ‰ ”‘”ŠŒ 120 ”Ö”‰. å ’ˆ‡¶ˆ‘ •” 60  ’”“— ’ÖŒ‹” ’Œ ˆ•–‰ˆŒ˜–Ø."

//	Resource: tSTR 1300
#define LossString                                1300	// "‚ˆ•–‰ˆŒ˜–Ø: êÖŒ‹”, Œ–‘ ‡”‘Ÿ¿Œ 59.  €‰—›, Œ–‘ ‡”‘Ÿ¿Œ 29.  ùŒ˜¶Œ›, Œ–‘ Œ–˜Ÿ ›”˜Ÿ ”Š’ˆ ‰Ø˜ˆ (‘ ‡‘ˆ •”“ˆ’ˆ ¶Œ–˜”‰ˆØ Šˆ“ˆ).  ¯Œ–˜, Œ–‘ ‰Ø˜” ’Œ˜."

//	Resource: tSTR 1200
#define CatchString                               1200	// "åˆ¿— æ¶Œ–˜”‰—ş Šˆ“— •”‡‘ˆ ¶Œ–˜”‰ˆØ ¿Œ–˜Ÿ •¶”˜‰’ˆ. å –‘ŒŠ—ş ¶ˆ ’Œ Š”•—–ˆ˜Œ ı˜”‹” - ‡ˆ‰‘Ø˜Œ–Ÿ ”˜ ¶Œ–˜”‰” Šˆ“ •¶ •Œ¶‰” ‰”“”¾’”–˜."

//	Resource: tSTR 1100
#define RulesString                               1100	// "ì¶ˆ‰‘ˆ ˆ¶˜”Ö’” ‹¶ "æ”Œ‘".  é‹¶ˆ –”–˜”˜  –Œ¶ ”’”‰. ì” ¶Œ—‘Ÿ˜ˆ˜ˆ“ ˆ¾Š”‹” ”’ˆ ”•¶ŒŠŒ‘Øş˜–Ø •¶”‹¶ˆ‰¿Œ  ¶ˆ“Œ¶ › •¶”‹¶¿ˆ (ˆ•–Ÿ Š‰—›, "

//	Resource: tSTR 1000
#define StatisticsString                          1000	// "„˜ˆ˜–˜ˆ •”Š–Ö˜‰ˆŒ˜–Ø –‘ŒŠ—ş“ ”‡¶ˆ”“.  ì¶”‹¶ˆ‰¿“: -1 Œ–‘ 12 -2 Œ–‘ 14 -4 Œ–‘ 16  å‹¶ˆ‰¿Œ“—: +4 Œ–‘ 0 +2 Œ–‘ 2  ‡”‘Ÿ¿Œ"


//	Resource: PICT 1011
#define Bitmap                                    1011

//	Resource: PICT 1012
#define Bitmap2                                   1012

//	Resource: PICT 2000
#define BitmapID2000Bitmap                        2000

//	Resource: PICT 1003
#define BitmapID1003Bitmap                        1003

//	Resource: PICT 1004
#define BitmapID1004Bitmap                        1004

//	Resource: PICT 1005
#define BitmapID1005Bitmap                        1005

//	Resource: PICT 2001
#define BitmapID2001Bitmap                        2001

//	Resource: PICT 2002
#define BitmapID2002Bitmap                        2002

//	Resource: PICT 1006
#define BitmapID1006Bitmap                        1006

//	Resource: PICT 1013
#define BitmapID1013Bitmap                        1013

//	Resource: PICT 1014
#define BitmapID1014Bitmap                        1014

//	Resource: PICT 1007
#define BitmapID1007Bitmap                        1007


//	Resource: tbmf 2000
#define LogoBitmapFamily                          2000


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

